# Generated by Django 4.2.1 on 2023-08-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_atama_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="atama",
            name="adress",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
