# Generated by Django 4.2.1 on 2024-03-29 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0003_atama_adress"),
    ]

    operations = [
        migrations.CreateModel(
            name="puanT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_plaka", models.CharField(max_length=40)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("devir_bakiye", models.IntegerField()),
                ("borc_bakiye", models.IntegerField()),
                ("alacak_bakiye", models.IntegerField()),
                ("toplam_bakiye", models.IntegerField()),
                (
                    "surucu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.drıver",
                    ),
                ),
            ],
        ),
    ]
