# Generated by Django 4.2.1 on 2024-03-29 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0004_puant"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="puanT",
            new_name="puanTable",
        ),
    ]
