# Generated by Django 4.2.1 on 2024-03-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0005_rename_puant_puantable"),
    ]

    operations = [
        migrations.AddField(
            model_name="puantable",
            name="adress",
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
