# Generated by Django 4.2.1 on 2024-03-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0006_puantable_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="puantable",
            name="daily_data",
            field=models.JSONField(default=list),
        ),
    ]
